server:
  port: 8082

spring:
  application:
    name: task-task-service
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.145.198.135:3306/task_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: task_user
    password: Task@2026!
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1

  data:
    redis:
      host: 192.168.10.11
      port: 6379
      database: 2
      timeout: 5000ms
      password: metaverse
      lettuce:
        pool:
          max-active: 8
          min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

admin:
  api:
    base-url: http://localhost:8084
internal:
  api-token: task-internal-2026

user:
  api-base-url: http://localhost:8081

jwt:
  secret: TaskPlatformSecretKey2026@AutoTask#$%^&*()_+1234567890

logging:
  level:
    com.task.platform: DEBUG
